CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','editor','seller','customer') NOT NULL DEFAULT 'customer',
  phone VARCHAR(20) NULL,
  document VARCHAR(20) NULL COMMENT 'CPF ou CNPJ',
  company_name VARCHAR(200) NULL,
  status ENUM('active','inactive','pending') NOT NULL DEFAULT 'active',
  email_verified_at DATETIME NULL,
  last_login_at DATETIME NULL,
  remember_token VARCHAR(100) NULL,
  password_reset_token VARCHAR(100) NULL,
  password_reset_expires_at DATETIME NULL,
  wp_legacy_id BIGINT UNSIGNED NULL COMMENT 'ID do WordPress original (migracao)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  INDEX idx_role (role),
  INDEX idx_status (status),
  INDEX idx_wp_legacy (wp_legacy_id),
  INDEX idx_password_reset (password_reset_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
