CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(20) NOT NULL UNIQUE COMMENT 'Ex: ORC-2026-00001',
  user_id BIGINT UNSIGNED NOT NULL COMMENT 'Cliente',
  created_by_user_id BIGINT UNSIGNED NULL COMMENT 'Vendedor que criou (se aplicavel)',
  quoted_by_user_id BIGINT UNSIGNED NULL COMMENT 'Vendedor que respondeu',
  status ENUM(
    'quote_requested',
    'quoted',
    'approved',
    'rejected',
    'expired',
    'pending_payment',
    'paid',
    'processing',
    'shipped',
    'delivered',
    'canceled'
  ) NOT NULL DEFAULT 'quote_requested',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  shipping_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  shipping_method VARCHAR(50) NULL,
  shipping_address_id BIGINT UNSIGNED NULL,
  payment_method VARCHAR(50) NULL,
  payment_status VARCHAR(30) NULL,
  payment_transaction_id VARCHAR(100) NULL,
  customer_notes TEXT NULL COMMENT 'Visivel ao cliente',
  internal_notes TEXT NULL COMMENT 'Apenas vendedor/admin',
  quoted_at DATETIME NULL,
  expires_at DATETIME NULL,
  approved_at DATETIME NULL,
  completed_at DATETIME NULL,
  canceled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_quoter FOREIGN KEY (quoted_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_address FOREIGN KEY (shipping_address_id) REFERENCES addresses(id),
  INDEX idx_user (user_id),
  INDEX idx_status (status),
  INDEX idx_created (created_at),
  INDEX idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
